/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse200Headers } from './inlineResponse200Headers';


export interface InlineResponse200 { 
    greeting?: string;
    date?: string;
    url?: string;
    headers?: InlineResponse200Headers;
}

